[[section-architecture-constraints]]
== Architecture Constraints


[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****

=== Technical constraints

[options="header",cols="1,2"]
|===
|Constraint|Description
| Github | Version control system. Mandatory for the project.
| Typescript | Programming language built in Javascript. Mandatory for the project.
| Solid | Specification that allows the users to store their personal data and give access to some of it to external applications.
| Data storage | Following the SOLID specification, the application must me structured in a way that does not store any personal information.
|===

=== Business constraints

[options="header",cols="1,2"]
|===
|Constraint|Description
| Schedule | The deadlines are set by the course teachers.
| Budget | Being students, we don't have budget for paid services or tools.
| Development team | The size and members of the team have been decided by the course teachers.
|===

|===
