[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****

=== Technology decisions
*ReactJS*

The frontend web application will be developed using React, one of the most used Javascript framework nowadays.

*MongoDB*

We will use Mongo as database engine, as we have already experience working with it and it is easy to maintain.

*NodeJS express + Typescript*

These will be the technologies we will use for the application backend. Typescript will be the main programming language for business logic and data access, and the REST API will be written using NodeJS express, a framework commonly used for this purpose.

=== Top-level decomposition
We decided to follow a MVC architectural pattern. This seems to us as the most straightforward way to develop the project, as this approach directly supports the use of different technologies on different layers.

=== How to achieve quality goals
In order to accomplish our privacy goals, we will try to reduce to the minimum the amount of information stored in our database. To accomplish Usability, we will try to follow the GUI standards and achieve minimum performance requirements in relation with response-time. In relation with code quality, we will keep an updated documentation and try to use design and architectural patterns when possible.

=== Organizational decisions constraints
At least one in-person team meeting will be done every week. More meetings will be organized via a discord server. Smaller details will be discussed via WhatsApp and the GitHub issues. We will keep track of the pending and done tasks with the kanban tool available in GitHub.
