[[section-solution-strategy]]
== Solution Strategy

=== Technology decisions

*ReactJS*

The frontend web application will be developed using React, one of the most used Javascript framework nowadays.

*MongoDB*

We will use Mongo as database engine, as we have already experience working with it and it is easy to integrate into TS/JS.

*NodeJS express + Typescript*

These will be the technologies we will use for the application backend. Typescript will be the main programming language for business logic and data access, and the REST API will be written using NodeJS express, a framework commonly used for this purpose.

*Docker on Ubuntu*

We use Docker running on an Ubuntu host to deploy the different parts of our application. This is one of the most common deployment configurations nowadays.

=== Top-level decomposition
We decided to follow an MVC architectural pattern. This seems to us as the most straightforward way to develop the project, as this approach directly supports the use of different technologies on different layers.

=== How to achieve quality goals
In order to accomplish our privacy goals, we will try to reduce to the minimum the amount of information stored in our database.
To accomplish usability, we will try to follow the GUI standards and achieve minimum performance requirements in relation with response-time.
In relation with maintainability, we will keep an updated documentation and try to use design and architectural patterns when possible.
The availability quality will be accomplished if we can maintain our application deployed forever.

=== Organizational decisions constraints
At least one in-person team meeting will be done every week. More meetings will be organized via a discord server when needed. Smaller details will be discussed via WhatsApp and the GitHub issues. We will keep track of the pending and done tasks with the kanban tool available in GitHub.
