[[section-design-decisions]]
== Design Decisions


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****

Here we will document the technologies that affect the application and we will be explaining why below.

=== Usage of MongoDB
[discrete]
===== Context
Since we need a Database to store the products for the application, not the users, they will be in their POD, we have to use a 
database, after thinking about it we decided we would use MongoDB since it has an easy connection with typescript.

=== Nominatim
[discrete]
===== Context
To calculate the distance between the central and the user direction we will make use of the Nominatim library.



//=== Usage of a library for notifications
//[discrete]
//===== Context
//The app must have a notification system for delivery.