name: CI for ASW2122

on:
  release:
    types: [ published ]

jobs:
  unit-test-webapp:
    env:
      SKIP_PREFLIGHT_CHECK: true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        env:
          API_URI: http://${{ secrets.DEPLOY_HOST }}:5000
          SKIP_PREFLIGHT_CHECK: true
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
        env:
          SKIP_PREFLIGHT_CHECK: true
      - uses: codecov/codecov-action@v2

  unit-test-restapi:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: restapi
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - uses: codecov/codecov-action@v2
  docker-push-webapp:
    name: Push webapp Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [ unit-test-webapp, unit-test-restapi ]
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@3.04
        env:
          API_URI: http://${{ secrets.DEPLOY_HOST }}:5000
          SKIP_PREFLIGHT_CHECK: true
        with:
          name: arquisoft/dede_en_01a/webapp
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
          registry: ghcr.io
          workdir: webapp
          buildargs: API_URI, SKIP_PREFLIGHT_CHECK
  docker-push-restapi:
    name: Push restapi Docker Image to GitHub Packages
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      PORT: ${{ secrets.PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    #needs: [e2e-tests]
    needs: [ unit-test-webapp, unit-test-restapi ]
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@3.04
        env:
          PRICE_PER_KM: ${{ secrets.PRICE_PER_KM }}
        with:
          name: arquisoft/dede_en_01a/restapi
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
          registry: ghcr.io
          workdir: restapi
          buildargs: PRICE_PER_KM, JWT_SECRET

  deploy:
    name: Deploy over SSH
    runs-on: ubuntu-latest
    needs: [ docker-push-restapi,docker-push-webapp ]
    steps:
      - name: Deploy over SSH
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          command: |
            wget https://raw.githubusercontent.com/Arquisoft/dede_en1a/deployment_workbench/docker-compose-deploy.yml -O docker-compose.yml
            docker-compose stop
            docker-compose rm -f
            docker-compose pull   
            docker-compose up -d